### ISSUE TITLE
URL Site Bug

### ISSUE THREAD

**Issue by LenoM** [phalcon/docs-app#156]
https://docs.phalconphp.com/3.4/en/tutorial.html
https://docs.phalconphp.com/3.4/en/install.html
https://docs.phalconphp.com/3.4/en/db.html
https://docs.phalconphp.com/3.4/en/samples.html
https://docs.phalconphp.com/3.4/en/tutorial-invo-2.html
https://docs.phalconphp.com/en/3.0.0/reference/volt.html
https://docs.phalconphp.com/pl/latest/reference/di.html
https://blog.phalconphp.com/post
https://blog.phalconphp.com/post/phosphorum-the-phalcons-forum
https://blog.phalconphp.com/post/20928554661/invo-a-sample-application

**Comment by niden** [comment]
All these have been addressed. Thank you @LenoM

**Comment by LenoM** [comment]
https://docs.phalconphp.com/en/latest/reference/routing.html#not-found-paths

**Comment by LenoM** [comment]
https://docs.phalconphp.com/en/latest/reference/dispatching.html

**Comment by LenoM** [comment]
https://docs.phalconphp.com/en/latest/reference/queue.html

**Comment by LenoM** [comment]
https://docs.phalconphp.com/en/latest/reference/micro.html
