### ISSUE TITLE
Make title clickable to anchor

### ISSUE THREAD

**Issue by ruudboon** [phalcon/docs-app#210]
If the title of an article contains an anchor we see the # in front. Can we make this title clickable so I can easily copy past the url with the anchor?

**Comment by ruudboon** [comment]
@Arhell Can you point me to the article template? I would like to create a pull to fix this but can't find where we generate this.

**Comment by Arhell** [comment]
Hi, sorry, I wanted to watch this issue this weekend.

**Comment by ruudboon** [comment]
@Arhell No problem at all.
Looks like it didn't work. On the docs we are using the js from the blog. And not the JS in this repo. Should a create a pull on the blog JS or should we change this to use local files?
CC @niden 
![Uploading Screenshot 2019-08-23 at 14.57.37.png…]()

**Comment by Arhell** [comment]
Of course, when I get free I will do

**Comment by ruudboon** [comment]
@Arhell I don't mind changing it. Do you want me to push this to the blog or change the link in the template?

**Comment by Arhell** [comment]
Merged, thank you @ruudboon

**Comment by ruudboon** [comment]
I know it’s my own pull but love that you can now click the titles and copy paste :)
Thnx for merging
