### ISSUE TITLE
Optimize performance

### ISSUE THREAD

**Issue by ruudboon** [phalcon/docs-app#216]
I've looked a bit into the performance of our docs.
I think we can speed it a up a bit more by doing the following.
- Load all fonts from google fonts
- Use smaller subset in google fonts (do we really need all the characters on all pages?)
- Ask Netlify to fix caching of files.

![Screenshot 2019-08-26 at 17 17 01](https://user-images.githubusercontent.com/7444246/63701497-5829f280-c825-11e9-9034-0bb4c64d3759.png)
![Screenshot 2019-08-26 at 17 16 37](https://user-images.githubusercontent.com/7444246/63701498-58c28900-c825-11e9-8c81-bd77c5bee764.png)
![Screenshot 2019-08-26 at 17 16 30](https://user-images.githubusercontent.com/7444246/63701499-58c28900-c825-11e9-9207-9526e09b8be2.png)

**Comment by sergeyklay** [comment]
@ruudboon What tool do you use? :thinking:

**Comment by niden** [comment]
@Arhell can we make the change for the google fonts?

**Comment by ruudboon** [comment]
@sergeyklay Webpagetest (Awesome tool for tunining) https://www.webpagetest.org/result/190826_4Z_304e01b62bb5af549ad2d77bb6e8b8db/

**Comment by Arhell** [comment]
Sure!

**Comment by Arhell** [comment]
Hi, I fixed then @niden  changed the file, please check, for my part I looked at Google everything in green
https://developers.google.com/speed/pagespeed/insights/?hl=RU&url=https%3A%2F%2Fdocs.phalcon.io%2F3.4%2Fen%2Fintroduction&tab=mobile

**Comment by niden** [comment]
I think Google is drunk. I clicked your link on my cellphone and it gave me orange (86%). Changed the language in the URL and reloaded the link I got 96% green

**Comment by Arhell** [comment]
cache?

**Comment by niden** [comment]
No idea my friend. Also the same link somehow did not load on my desktop :/ 

I think we can do some work in minifying the assets before we send them upstream. I sent you a link on Discord about it.

**Comment by Arhell** [comment]
add min.css and upd fonts

**Comment by ruudboon** [comment]
@Arhell Thnx! That helped a lot. We're almost a second down.

https://www.webpagetest.org/result/190919_RA_c424b4ca5e24749c6c21d9d6a129ddd6/
