### ISSUE TITLE
Lowercase url's in sitemap

### ISSUE THREAD

**Issue by ruudboon** [phalcon/docs-app#220]
I'm seeing some issues regarding our sitemap.
Our sitemap contains url's with uppercase characters while our webserver is only serving lowercase (redirect if you enter uppercase). This is causing issues with indexing.

Don't think this is possible yet with out plugin. Opened an issue to this feature. See https://github.com/jekyll/jekyll-sitemap/issues/251

**Comment by niden** [comment]
We can create our own sitemap script. Not that difficult to do if they do not respond

**Comment by ruudboon** [comment]
@niden Let's go for our own implementation. Looking at the history of the project I'm not expecting an update anytime soon.

**Comment by niden** [comment]
This has been implemented and released

**Comment by ruudboon** [comment]
Thnx!
