### ISSUE TITLE
Extra escaping?

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/docs-app#29]
Fully qualified class names should be `Phalcon\Mvc\View\Simple` instead of `Phalcon\\Mvc\\View\\Simple`.

https://docs.phalconphp.com/ru/latest/application-micro

<img width="824" alt="screen shot 2017-07-10 at 11 07 55 am" src="https://user-images.githubusercontent.com/1256298/28008406-18a5c078-6560-11e7-9e22-5242c65f9aed.png">

https://docs.phalconphp.com/en/latest/application-micro

<img width="846" alt="screen shot 2017-07-10 at 11 11 26 am" src="https://user-images.githubusercontent.com/1256298/28008527-90b8a33c-6560-11e7-82a1-8eb0ac8f2d01.png">

**Comment by sergeyklay** [comment]
https://docs.phalconphp.com/en/latest/volt

`'compileAlways' => true`

<img width="855" alt="screen shot 2017-07-10 at 11 54 01 am" src="https://user-images.githubusercontent.com/1256298/28010153-a030133a-6566-11e7-98e0-83e60be84b68.png">

**Comment by niden** [comment]
That could be either crowdin or parsedown. We need to check it out

**Comment by niden** [comment]
Contacted crowdin for possible solutions. This happens only on the `div` that contains the alert/warning. The data is escaped which produces the volt screenshot side effect as well as the application-micro one with the class name.

**Comment by sergeyklay** [comment]
@ninjapanzer Could you please take a look

**Comment by ninjapanzer** [comment]
The `https://docs.phalconphp.com/en/latest/volt` page is a parsedown issue
```
$Extra = new ParsedownExtra();
echo $Extra->text("Volt with the option <code>'compileAlways' => true</code>. Thus, the") . PHP_EOL;
```
Output
```
<p>Volt with the option <code>'compileAlways' =&gt; true</code>. Thus, the</p>
```

I believe the other one is likely an issue with Crowdin. The `en` version is structured differently than the ru
en
```
<div class='alert alert-warning'>
    <p>
        The above example uses the <a href="/[[language]]/[[version]]/Phalcon_Mvc_View_Simple">Phalcon\Mvc\View\Simple</a> component, which uses relative paths instead of controllers and actions. You can use the <a href="/[[language]]/[[version]]/Phalcon_Mvc_View">Phalcon\Mvc\View</a> component instead, but to do so you will need to change the parameters passed to <code>render()</code>`
    </p>
</div>
```
ru
```
<h5 class='alert alert-warning'>The above example uses the <code>Phalcon\\Mvc\\View\\Simple</code> component, which uses relative paths instead of controllers and actions. You can use the <code>Phalcon\\Mvc\\View</code> component instead, but to do so you will need to change the parameters passed to <code>render()</code></h5>
```

The extra escapes are in the ru markdown.

I checked it against parsedown to be sure
```
$Extra = new ParsedownExtra();
$data = '<div class=\'alert alert-warning\'><p>The above example uses the <a href="/[[language]]/[[version]]/Phalcon_Mvc_View_Simple">Phalcon\Mvc\View\Simple</a> component, which uses relative paths instead of controllers and actions. You can use the <a href="/[[language]]/[[version]]/Phalcon_Mvc_View">Phalcon\Mvc\View</a> component instead, but to do so you will need to</p></div>';

$language = 'en';
$version = '3.2';
/**
 * Language and version
 */
$data = str_replace(
    [
        '[[language]]',
        '[[version]]',
        '0#', '1#', '2#', '3#', '4#',
        '5#', '6#', '7#', '8#', '9#',
        '0`', '1`', '2`', '3`', '4`',
        '5`', '6`', '7`', '8`', '9`',
    ],
    [
        $language,
        $version,
        '#', '#', '#', '#', '#',
        '#', '#', '#', '#', '#',
        '`', '`', '`', '`', '`',
        '`', '`', '`', '`', '`',
    ],
    $data
);

echo $Extra->text($data) . PHP_EOL;
```

**Comment by sergeyklay** [comment]
Closing, this is fixed. If there are bugs, we can follow up in separate issues.
