### ISSUE TITLE
404: Something went wrong.

### ISSUE THREAD

**Issue by yesworld** [phalcon/docs-app#467]
This page: https://docs.phalcon.io/5.0/en/tutorial-rest
has a link: https://docs.phalcon.io/5.0/en/rest-api
In NOTE section: _You can also have a look at the [rest-api](https://docs.phalcon.io/5.0/en/rest-api) project._

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/docs-app/commit/076040544b16e17cf40809891ee866331697386c

Thank you @yesworld
