### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by d47081** [phalcon/docs-app#473]
On dark theme environment the website looks like this

![Pasted image](https://github.com/phalcon/docs-app/assets/108541346/4ec4ab4d-a377-43be-94a1-d3aa9e78210a)

At least, would be nice to define `backgound:white` for the `body` tag, but I don't know where to fix it properly.

**Comment by niden** [comment]
Fixed in https://github.com/phalcon/docs-app/pull/474
