### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by emiliodeg** [phalcon/docs-app#90]
Reviewing the application of the documentation a bit I found these 2 errors

1. The [home page](https://docs.phalconphp.com/en/3.4/) does not have support to translate to other languages
2. Correct flags that represent languages. currently for the arabic language the flag of **AR**gentina is shown, check the rest of the flags

@niden if you want I can take care of them

**Comment by niden** [comment]
@emiliodeg If you have time sure. Have a look on how it is done here:

https://github.com/phalcon/zephir-docs-app/blob/master/app/tasks/GetLanguagesTask.php

and then 

https://github.com/phalcon/zephir-docs-app/blob/master/app/views/inc/header-languages.volt

If we can leverage the Crowdin API to retrieve the languages then it would make the task much easier. The `languages.json` can be generated with every deployment which is pretty much when we do a git pull and get all the new translated text.

This way we won't have to worry about updating the dropdown. I intend on doing the same thing for the zephir website as well as the phalcon website.

**Comment by emiliodeg** [comment]
What do you think with only show languages > 0% traslated?

**Comment by emiliodeg** [comment]
ok then we could put a legend when entering incomplete translations. "the translation is at 42% please help us complete it" with a link to crowding. What do you think?

**Comment by niden** [comment]
Yeah we can do that for sure. Where to put it I don't know yet. The Crowdin API offers information about translated strings etc. so we can easily calculate the % complete.

**Comment by niden** [comment]
This has been addressed

**Comment by emiliodeg** [comment]
You have finished before me
I thought that I had to take care of this and I had it done at 70%
